// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;
using PrawoRAG.Storage;

#nullable disable

namespace PrawoRAG.Storage.Migrations
{
    [DbContext(typeof(PrawoRagDbContext))]
    [Migration("20260704150728_LockEmbeddingModelLargeV2_1024")]
    partial class LockEmbeddingModelLargeV2_1024
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrawoRAG.Storage.Entities.ChunkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CharEnd")
                        .HasColumnType("integer");

                    b.Property<int>("CharStart")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmbeddedWith")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)");

                    b.Property<JsonDocument>("Locator")
                        .HasColumnType("jsonb");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(\"Text\", ''))", true);

                    b.Property<string>("Section")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmbeddedWith");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("chunks", (string)null);
                });

            modelBuilder.Entity("PrawoRAG.Storage.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourtType")
                        .HasColumnType("text");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<bool?>("InForce")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("JudgmentDate")
                        .HasColumnType("date");

                    b.PrimitiveCollection<string[]>("QualityIssues")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SourceModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("TypedMetadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourtType");

                    b.HasIndex("InForce");

                    b.HasIndex("Status");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.HasIndex("Source", "SourceModificationDate");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("PrawoRAG.Storage.Entities.SyncStateEntity", b =>
                {
                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Source");

                    b.ToTable("sync_state", (string)null);
                });

            modelBuilder.Entity("PrawoRAG.Storage.Entities.ChunkEntity", b =>
                {
                    b.HasOne("PrawoRAG.Storage.Entities.DocumentEntity", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("PrawoRAG.Storage.Entities.DocumentEntity", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
